plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.3.10'
    id "maven-publish"
}

group = 'inc.kaizen.client'
version = '1.0'

repositories {
    mavenCentral()
    maven {
        url = "https://maven.pkg.github.com/kaizen-inc/Podium"
    }
}

dependencies {
    implementation libs.kotlin.stdlib

    implementation libs.okhttp.logging
    implementation libs.retrofit.core
    implementation libs.retrofit.converter.gson
    implementation libs.retrofit.converter.scalars
    implementation libs.coroutines.core

    implementation libs.podium

    testImplementation libs.kotest.runner.junit5
    testImplementation libs.kotest.assertions.core
    testImplementation libs.kotest.property

    testImplementation libs.kotlin.test

    testImplementation libs.mockk

    testImplementation libs.okhttp.mockwebserver
    testImplementation libs.coroutines.test
    testImplementation libs.jsonpath
}

test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(21)
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/kaizen-inc/ocktogon")
        }
    }
    publications {
        maven(MavenPublication) {
            from(components.java)
        }
    }
}