plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.0'
    id "maven-publish"
}

group = 'inc.kaizen.client'
version = '0.1'

repositories {
    mavenCentral()
    maven {
        url = "https://maven.pkg.github.com/kaizen-inc/Podium"
        credentials {
            username GITHUB_ACTOR
            password GITHUB_TOKEN
        }
    }
}

dependencies {
    var kotlin_version = '1.9.0'
    var retrofitVersion = '2.9.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"

    implementation "com.squareup.okhttp3:logging-interceptor:4.9.1"
    implementation "com.squareup.retrofit2:retrofit:$retrofitVersion"
    implementation "com.squareup.retrofit2:converter-gson:$retrofitVersion"
    implementation "com.squareup.retrofit2:converter-scalars:$retrofitVersion"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4'

    implementation 'inc.kaizen.base:podium:0.1'

    def version = "5.5.4"
    testImplementation "io.kotest:kotest-runner-junit5:$version"
    testImplementation "io.kotest:kotest-assertions-core:$version"
    testImplementation "io.kotest:kotest-property:$version"

    testImplementation 'org.jetbrains.kotlin:kotlin-test'

    def mockkVersion = "1.13.2"
    testImplementation "io.mockk:mockk:${mockkVersion}"
}

test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(8)
}