package inc.kaizen.client.ocktogon.pull.model.pull

import inc.kaizen.client.common.*

data class Pull(
    val _links: PullRequestLinks? = null,
    val active_lock_reason: String? = null,
    val additions: Int? = null,
    val assignee: User? = null,
    val assignees: List<User>? = null,
    val author_association: String? = null,
    val auto_merge: Any? = null,
    val base: Head? = null,
    val body: String? = null,
    val changed_files: Int? = null,
    val closed_at: String? = null,
    val comments: Int? = null,
    val comments_url: String? = null,
    val commits: Int? = null,
    val commits_url: String? = null,
    val created_at: String? = null,
    val deletions: Int? = null,
    val diff_url: String? = null,
    val draft: Boolean? = null,
    val head: Head? = null,
    val html_url: String? = null,
    val id: Int? = null,
    val issue_url: String? = null,
    val labels: List<Label>? = null,
    val locked: Boolean? = null,
    val maintainer_can_modify: Boolean? = null,
    val merge_commit_sha: String? = null,
    val mergeable: Boolean? = null,
    val mergeable_state: String? = null,
    val merged: Boolean? = null,
    val merged_at: String? = null,
    val merged_by: User? = null,
    val milestone: Milestone? = null,
    val node_id: String? = null,
    val number: Int? = null,
    val patch_url: String? = null,
    val rebaseable: Boolean? = null,
    val requested_reviewers: List<User>? = null,
    val requested_teams: List<Team>? = null,
    val review_comment_url: String? = null,
    val review_comments: Int? = null,
    val review_comments_url: String? = null,
    val state: String? = null,
    val statuses_url: String? = null,
    val title: String? = null,
    val updated_at: String? = null,
    val url: String? = null,
    val user: User? = null
)