package inc.kaizen.client.ocktogon.common

data class Team(
    val id: Int? = null,
    val node_id: String? = null,
    val url: String? = null,
    val html_url: String? = null,
    val name: String? = null,
    val slug: String? = null,
    val description: String? = null,
    val privacy: String? = null,
    val notification_setting: String? = null,
    val permission: String? = null,
    val members_url: String? = null,
    val repositories_url: String? = null,
    val parent: Team? = null,
    val members_count: Int? = null,
    val repos_count: Int? = null,
    val created_at: String? = null,
    val updated_at: String? = null,
    val organization: Organization? = null
)

data class Organization(
    val id: Int? = null,
    val login: String? = null,
    val node_id: String? = null,
    val url: String? = null,
    val repos_url: String? = null,
    val events_url: String? = null,
    val hooks_url: String? = null,
    val issues_url: String? = null,
    val members_url: String? = null,
    val public_members_url: String? = null,
    val avatar_url: String? = null,
    val description: String? = null,
    val name: String? = null,
    val company: String? = null,
    val blog: String? = null,
    val location: String? = null,
    val email: String? = null,
    val twitter_username: String? = null,
    val is_verified: Boolean? = null,
    val has_organization_projects: Boolean? = null,
    val has_repository_projects: Boolean? = null,
    val public_repos: Int? = null,
    val public_gists: Int? = null,
    val followers: Int? = null,
    val following: Int? = null,
    val html_url: String? = null,
    val type: String? = null,
    val total_private_repos: Int? = null,
    val owned_private_repos: Int? = null,
    val private_gists: Int? = null,
    val disk_usage: Int? = null,
    val collaborators: Int? = null,
    val billing_email: String? = null,
    val plan: Plan? = null,
    val default_repository_permission: String? = null,
    val members_can_create_repositories: Boolean? = null,
    val two_factor_requirement_enabled: Boolean? = null,
    val members_allowed_repository_creation_type: String? = null,
    val members_can_create_public_repositories: Boolean? = null,
    val members_can_create_private_repositories: Boolean? = null,
    val members_can_create_internal_repositories: Boolean? = null,
    val members_can_create_pages: Boolean? = null,
    val members_can_create_public_pages: Boolean? = null,
    val members_can_create_private_pages: Boolean? = null,
    val members_can_fork_private_repositories: Boolean? = null,
    val web_commit_signoff_required: Boolean? = null,
    val created_at: String? = null,
    val updated_at: String? = null,
    val archived_at: String? = null
)

